version: '2.1'

services:

  bslayer:
    image: bslayer
    container_name: bslayer
    build:
      context: .
      dockerfile: bs-layer/Dockerfile    
    expose:
      - 8080
    ports:
      - '8021:8080'

